Preparation for enowars CTF
C4T-BuT-S4D/neo pull request #17
Opened 2022-07-15 13:35 UTC by pomo-mondreganto

2023-01-18 14:37 UTC, jnovikov requested changes

2023-01-18 14:37 UTC, jnovikov commented on internal/server/server.go
> +const (
не уверен что по кодстайлу так, но кажется можно в 1 блок констант объединить

2023-01-18 14:37 UTC, jnovikov commented on internal/server/server.go
> +		if (i-1)%logLinesBatchSize == 0 {
nit: я бы делал наоборот +1 чтобы точно не брать модуль от отриц числа.

2023-01-18 14:37 UTC, jnovikov commented on internal/server/storage_test.go
> +	require.Len(t, cs.States(), 1)
можно эту проверку наверх, чтобы сначала проверить длину, потом уже контент

2023-01-18 14:37 UTC, jnovikov commented on pkg/gstream/dynsize.go
> +func (d *DynamicSizeCache[T, M]) flushUnsafe() error {
меня немного смущает название unsafe тут. 

Кажется можно оставить просто flush() ?

2023-01-18 14:37 UTC, jnovikov commented on pkg/gstream/dynsize.go
> +	d.queue = nil
Кажется для пущего перфа правильнее будет сделать что-то около 
d.queue = d.queue[:0], чтобы не реаллоцировать опять.

2023-01-18 14:37 UTC, jnovikov commented on pkg/gstream/dynsize_test.go
> +	t.Run("simple", func(t *testing.T) {
я бы разделил на 2 теста, Run обычно для table-тестов юзают все-таки

2023-01-18 14:37 UTC, jnovikov commented on pkg/hostbucket/hostbucket_test.go
> +			require.Len(t, ipb.Teams, wantn)
кажется что эту проверку можно вообще убрать, ее покроет cmp.Diff

2023-01-18 14:37 UTC, jnovikov commented on pkg/hostbucket/hostbucket_test.go
>  		t.Logf("Mean std dev: %f", meanStdDev)
А может убрать ?

2023-01-18 14:37 UTC, jnovikov commented on pkg/hostbucket/hostbucket_test.go
> +		require.True(t, meanStdDev <= tc.maxMeanStdDev)
require.LessOrEqual ?

2023-07-23 01:38 UTC, pomo-mondreganto commented on client_env/start.sh
> +    --network host \
Иногда удобно

2023-07-23 01:38 UTC, pomo-mondreganto commented on cmd/server/main.go
> +	reflection.Register(s)
Удобно

2023-07-27 12:05 UTC, pomo-mondreganto commented on pkg/hostbucket/hostbucket_test.go
> +			require.Len(t, ipb.Teams, wantn)
не покроет, если ключи одинаковые

2023-07-27 12:06 UTC, pomo-mondreganto commented on pkg/hostbucket/hostbucket_test.go
>  		t.Logf("Mean std dev: %f", meanStdDev)
Почему бы и нет?

2023-08-15 22:35 UTC, jnovikov requested changes

2023-08-15 22:35 UTC, jnovikov commented on internal/exploit/runner.go
> +	startLoops := func() {
Вкусовщина, но я бы сделал отдельный метод, 

func (r *Runner) runWorkers(ctx context.Context, wg *sync.WaitGroup) context.CancelFunc

Чтобы тут в методе было что-то около

var workersWg sync.WaitGroup

cancelWorkers := runWorkers(ctx, &workersWg);

2023-08-15 22:35 UTC, jnovikov commented on internal/exploit/submit_loop.go
> +	queueCache := make(map[string]struct{})
В теории хорошо было бы тут сделать LRU, но пофиг скорее

2023-08-15 22:35 UTC, jnovikov commented on internal/queue/output.go
> +	Exploit *models.Exploit
Можно без указателя вроде тоже

2023-08-15 22:35 UTC, jnovikov commented on internal/queue/simple_factory.go
> +func NewSimpleQueueFactory() Factory {
Возвращай конкретное значение лучше

2023-08-15 22:36 UTC, jnovikov requested changes
Немного комментов

2023-08-19 16:07 UTC, pomo-mondreganto commented on lib/proto/neo.proto
> +    rpc SingleRunRequests(google.protobuf.Empty) returns (stream SingleRunRequest) {}
Первый для клиентов (попросить запустить), второй для раннеров (стриминговая апишка, в которую сервер запросы рассылает)

2023-08-19 16:07 UTC, pomo-mondreganto commented on cmd/client/cli/add.go
> +	"google.golang.org/protobuf/types/known/durationpb"
Так нельзя, дублирование названия пакета

2023-08-19 16:08 UTC, pomo-mondreganto commented on cmd/client/cli/cli.go
> +	if id := viper.GetString("client_id"); id != "" {
Скорее через env

2023-08-19 16:09 UTC, pomo-mondreganto commented on proto/exploits/api.proto
Тут мне просто так больше понравилось

2023-08-19 16:10 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +func CreateExploitJobs(
Мне лень думать, где я могу менять значения, а где не могу (где не указатель), перфа это ровно 0 добавляет, поэтому проще тупо везде указатели использовать

2023-08-19 16:11 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	logSender joblogger.Sender,
> можно было запустить без logSender (или с dummy log sender to Stdout)

такое уже есть, sender -- интерфейс, для него есть dummy реализация, она даже используется где-то 

> были дефолты для maxJobs, maxEndless

если было это было в pkg, норм, но для internal функции пакета оверкил

2023-08-19 16:12 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	logSender joblogger.Sender,
В целом я только за использовать функциональные опции, но в коде (не в тестах) эта функция используется буквально 1 раз, поэтому не особо имеет смысл, имхо

2023-08-19 16:12 UTC, pomo-mondreganto commented on pkg/neoproc/reaper.go
> +	if os.Getpid() != 1 {
Да

2023-08-19 16:13 UTC, pomo-mondreganto commented on pkg/neoproc/reaper.go
> +	c := make(chan os.Signal, 5)
1 мало (можем не успеть второй обработать, пока обрабатываем первый), 10 много, 5 в самый раз...

2023-08-19 16:13 UTC, pomo-mondreganto commented on pkg/neoproc/reaper.go
> +				pid, err := syscall.Wait4(-1, &wstatus, 0, nil)
У процессов могут быть дети (внуки раннера), их тоже нужно собирать

2023-08-19 16:14 UTC, pomo-mondreganto commented on pkg/neosync/wg.go
> +type WaitGroup struct {
Я это сначала написал, заиспользовал в 10 местах, а потом 9 из 10 мест стер. Согласен, надо убрать

2023-08-19 16:17 UTC, pomo-mondreganto commented on cmd/server/main.go
> -		return fmt.Errorf("creating file watcher: %w", err)
Да

2023-08-19 16:22 UTC, pomo-mondreganto commented on internal/exploit/storage.go
> +	if entryPath, err = saveExploit(f, oPath, resp.State.Config); err != nil {
Она будет выше, когда мы файл попытаемся скачать (ну и state не может быть nil)

2023-08-19 16:23 UTC, pomo-mondreganto commented on internal/exploit/storage.go
> +	if resp.State.Config.IsArchive {
Тут уже ладно, больше уровень вложенности

2023-08-19 16:23 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +func NewRunner(
Нет смысла, нет юзкейса

2023-08-19 16:26 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	case r.restarts <- struct{}{}:
Если несколько челов попросят рестарт (поменялись и команды, и эксплоиты, например), нам достаточно 1 этого обновления

2023-08-19 16:27 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +			r.restartLoops()
Так и сделано, см. выше

2023-08-19 16:28 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	select {
Здесь нет смысла менять размер буфера, паттерн как раз в дедубликации запросов обновления

2023-08-19 16:28 UTC, pomo-mondreganto commented on internal/exploit/submit_loop.go
> +	queueCache := make(map[string]struct{})
Нет, совсем старые флаги тоже хочется отсеивать (а памяти это 0 занимает, миллион флагов у нас никогда не было)

2023-08-21 14:39 UTC, pomo-mondreganto commented on proto/exploits/api.proto
> +  oneof payload {
Раньше так было, было менее удобно расширять

2023-08-21 14:40 UTC, pomo-mondreganto commented on internal/client/client.go
> +	epb "github.com/c4t-but-s4d/neo/proto/go/exploits"
Добавил (и запустил) 

```
.PHONY: goimports
goimports:
	goimports -local github.com/c4t-but-s4d/neo -w -d $(find . -type f -name '*.go' -not -path "./proto/*")

```

2023-08-21 15:02 UTC, pomo-mondreganto commented on internal/models/exploit.go
Там циклические зависимости на эту структуру

2023-08-21 15:05 UTC, pomo-mondreganto commented on internal/exploit/storage.go
> +	if entryPath, err = saveExploit(f, oPath, resp.State.Config); err != nil {
Добавил проверок

2023-08-21 15:06 UTC, pomo-mondreganto commented on internal/queue/simple_factory.go
> +func NewSimpleQueueFactory() Factory {
Для этого надо тип сделать публичным (публичная функция не может возвращать приватный тип), а этого не особо хочется

2023-08-23 13:01 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	startLoops := func() {
Хотя мб и нормально

2023-09-26 18:47 UTC, merged